import { StyleSheet } from "react-native";

export default StyleSheet.create({
    ScrollView: { padding: 30 },
    container: {
        flex: 1,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: "#eeeeee",
      },
    icons: {
        marginTop: 30,
        flexDirection: "row",
        justifyContent: 'space-between',
        },
    titleFp: {
        fontFamily:"Avenir",
        fontSize: 33,
        fontWeight: "bold",
        marginBottom: 24,
        textAlign: "center",
        color: "#333333",
        },
    imageFp: {
        marginBottom: 100,
        height: 280,
        width: 280,
        borderRadius: 1800
  },
    bodyFp:{
        fontFamily:"Avenir",
        fontSize: 15,
        textAlign: "center",
        color: "#333333",
      }, 
    view:{
        backgroundColor:"#aaaaaa",
        fontFamily:"Avenir",
        fontSize: 15,
      },
    list: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
        borderRadius: 50,
        padding: 20,
        marginLeft: "auto",
        marginRight: "auto",
        margin: 10,
        borderWidth: StyleSheet.hairlineWidth,
        backgroundColor: "#ffffff",
    },
    body: {
        fontFamily: "Avenir",
        fontSize: 15,
        textAlign: "center",
        color: "#333333",
    },
    left: {
        textAlign: "left",
    },
    image: {
        resizeMode: "contain",
        height: 300,
        width: 300,
        justifyContent: "center",
        alignItems: "center",
        marginTop: "auto",
        marginBottom: "auto",
        marginLeft: "auto",
        marginRight: "auto",
    },
    profileImage: {
        height: 300,
        width: "100%",
    },
    profileImageSmall: {
        height: 70,
        width: 70,
        borderRadius: 70,
        margin: 10,
        marginRight: 20,
        justifyContent: "center",
        alignItems: "center",
        marginTop: 20,
        marginBottom: 20,
    },
    bookListImage:{
        resizeMode: "contain",
        borderRadius: 50,
        height: 300,
        width: 300,
        justifyContent: "center",
        alignItems: "center",
        marginTop: 40,
        padding: 10,
        },
    button: {
        alignItems: "center",
        paddingVertical: 12,
        paddingHorizontal: 22,
        margin: 10,
        borderRadius: 30,
        elevation: 3,
        backgroundColor: "#dddddd",
    },
    search: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
        padding: 20,
        margin: 12,
        height: 40,
        borderWidth: 1,
        borderRadius: 30,
      },
    desc: {
        fontFamily: "Avenir",
        fontSize: 15,
        textAlign: "center",
        color: "#333333",
        padding: 30,
        paddingBottom: 10,
        textAlign: "justify",
    },
    title: {
        fontFamily: "Avenir",
        fontWeight: "bold",
        fontSize: 19,
        textAlign: "center",
        color: "#333333",
        paddingTop: 20,
        paddingHorizontal: 20
          },
    bookListTitle:{
        fontFamily:"Avenir",
        fontSize: 16,
        textAlign: "center",
        color: "#333333",
        padding: 10,
        marginBottom: 10
        },
    containerProfile: {
        flexDirection: "row",
        justifyContent: "center",
        },
        bodyProfile: {
            marginTop: 10,
            fontFamily: "Avenir",
            fontSize: 15,
            padding: 5,
            justifyContent: "center",
            textAlign: "center",
            color: "#333333",
        },
        buttonProfile: {
            alignItems: "center",
            paddingVertical: 12,
            paddingHorizontal: 22,
            margin: 10,
            borderRadius: 4,
            elevation: 3,
            backgroundColor: "#dddddd",
        },
    bold: {
        fontWeight:"bold",
        fontSize: 17,
    },
    interactionsBody : {
        marginVertical: 5,
    }
});
